### ISSUE TITLE
可以显示县，那为什么不能显示省及城市名称呢？

### ISSUE THREAD

**Issue by dongyuechuwu** [onewesong/IDCardNumParse#1]
RT，

![1650534814(1)](https://user-images.githubusercontent.com/14136324/164429773-33198d08-ca8b-4d74-bbe1-82f62c0347ac.png)

有些时候就是为了获取到它所在的省份及城市啊

**Comment by onewesong** [comment]
![image](https://user-images.githubusercontent.com/17920822/167233889-1d61b1c0-bbf6-4c3b-a667-777cffa366cc.png)
输入的时候就知道了
